### PR TITLE
[v0.4] Update dependencies

### PR DESCRIPTION
**Pull request by tnozicka**
Updates dependencies to get the newest bug fixes.

#### Requires
- [x] https://github.com/scylladb/local-csi-driver/pull/58

### CODE REVIEW

**Comment by tnozicka** [comment]
https://github.com/scylladb/local-csi-driver/issues/49#issuecomment-2232980254
/retest

**Review by zimnx — APPROVED** [review]
lgtm, please fix commit message to indicate dependency updates

**Comment by tnozicka** [comment]
fixed, thx

**Comment by tnozicka** [comment]
https://github.com/scylladb/local-csi-driver/issues/49#issuecomment-2235960753
/retest

**Pull request merged**
